### ISSUE TITLE
rename dropCollection to deleteCollection

### ISSUE THREAD

**Issue by nicoloboschi** [datastax/astra-db-ts#21]

**Comment by toptobes** [comment]
Probably won't do so, so as to align with Mongo's name scheme. I'll leave the issue open for now in case anyone else has something else to say

**Comment by nicoloboschi** [comment]
@toptobes can you elaborate ? Data API and astrapy uses the verb "delete" and not drop

**Comment by toptobes** [comment]
Sure thing. We're aligning ourselves with Mongo's own API to have the most "transferable" CRUD experience possible, since Mongo's API is well established already. 

I believe it's actually on the todo-list for astra.py to rename theirs to `drop_collection()` as well

This is the function in question we're naming our own after
https://mongodb.github.io/node-mongodb-native/6.3/classes/Db.html#dropCollection
